### ISSUE TITLE
Video playback

### ISSUE THREAD

**Issue by Ashukat** [crowd-course/interactivelearningsystem#3]
@rvaish pointed out following

> small improvement may be required, the moment  I run code - video resumes - most of the times, people may want to understand the result - then try something else with it — so control may be given to the user to resume the video, rather than auto start

In addition to this, we should also disable the playback until the user completes the task/question.

**Comment by imjching** [comment]
We're left with "disable the playback until the user completes the task/question". I think this can be put aside for now since it isn't a priority (I guess..).
